# Generated by Django 4.2.1 on 2023-05-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название нового продукта')),
            ],
            options={
                'verbose_name': 'Название нового продукта',
                'verbose_name_plural': 'Название новыйх продуктов',
            },
        ),
    ]
