# Generated by Django 4.2.1 on 2023-05-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='developer',
            field=models.CharField(max_length=150, null=True, verbose_name='Разработчик'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(max_length=150, null=True, verbose_name='Издатель'),
        ),
    ]
