# Generated by Django 4.2.1 on 2023-05-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_product_developer_product_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.DateField(null=True, verbose_name='Дата выхода'),
        ),
    ]
